INSERT INTO Album(ID, Titel, Uitgiftejaar, Single) VALUES (0, 'Black Album', 1991, 'Album');
INSERT INTO Album(ID, Titel, Uitgiftejaar, Single) VALUES (1, 'Bad Vibrations', 2016, 'Album');
INSERT INTO Album(ID, Titel, Uitgiftejaar, Single) VALUES (2, 'All I Want (acoustic)', 2011, 'Single');
INSERT INTO Album(ID, Titel, Uitgiftejaar, Single) VALUES (3, 'Attack Of The Killer B-Sides', 2010, 'Single');
INSERT INTO Album(ID, Titel, Uitgiftejaar, Single) VALUES (4, 'Californication', 1999, 'Album');
INSERT INTO Album(ID, Titel, Uitgiftejaar, Single) VALUES (5, 'A Day At The Races', 1976, 'Album');
INSERT INTO Album(ID, Titel, Uitgiftejaar, Single) VALUES (6, 'All The Gods Have Abandoned Us', 2016, 'Album');
INSERT INTO Album(ID, Titel, Uitgiftejaar, Single) VALUES (7, 'Herzeleid', 1995, 'Album');
INSERT INTO Album(ID, Titel, Uitgiftejaar, Single) VALUES (8, 'Dead Inside', 2015, 'Single');
INSERT INTO Album(ID, Titel, Uitgiftejaar, Single) VALUES (9, 'Psycho', 2015, 'Single');